import { useState } from "react";
import Head from "next/head";
import { dedupExchange, fetchExchange, useQuery } from "urql";
import { cacheExchange } from "@urql/exchange-graphcache";
import { withUrqlClient } from "next-urql";
import { devtoolsExchange } from "@urql/devtools";

import CartTotal from "../components/CartTotal";
import styles from "../styles/Home.module.css";

function Home() {
  const [showTotals, setShowTotals] = useState(true);
  const [result] = useQuery({
    query: `
    query Cart {
      cart {
        id
        total
        products {
          id
          name
          price
        }
      }
    }`,
    requestPolicy: "cache-and-network",
    pause: typeof window === "undefined",
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Cart</h1>
        {result.data?.cart.products.map((product: any) => (
          <p key={product.id}>
            {product.name}: ${product.price}
          </p>
        ))}
        <p>Total: ${result.data?.cart.total}</p>
        <br />
        <br />

        <button onClick={() => setShowTotals(!showTotals)}>
          toggle totals
        </button>
        {showTotals && <CartTotal />}
      </main>
    </>
  );
}

export default withUrqlClient(
  (ssr, _ctx) => {
    return {
      url: "/api/graphql",
      exchanges: [
        ssr,
        devtoolsExchange,
        dedupExchange,
        cacheExchange({}),
        fetchExchange,
      ],
    };
  },
  { ssr: true }
)(Home);
